Test014:
	output is blank
	  - is a Null pointer exception I was trying to do a try catch but ran
	    out of time.
	    For example try { ... } catch (RuntimeException &e){ ... }

Test015
Test016:
	printHeader: output is blank

Test017:
	printMain: methods are missing "(a)" as parameter
		   "__vptr->" missing in front of self(a)
		   constructor missing "(5)" as parameter
		   self(var) and self(method) cannot be named the same

Test018:
	printMain: int should be int32_t
		   should x be moved to somewhere else since it is global

Test019:
	printMain: int should be int32_t

Test020:
	how is this supposed to be

Full Translation from test000->test003
